AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Serverless GitHub app

Parameters:
  awsRole:
    Description: The AWS ARN role
    Type: String
  functionName:
    Description: The AWS Lambda's Function name
    Type: String
  hostedZoneId:
    Description: ID of the Hosted zone where static record set will be created
    Type: String
  fullDomainName:
    Description: Full domain name of the record set
    Type: String
  tlsCertificateArn:
    Description: ARN of the TLS certificate needed for the API Gateway custom domain name
    Type: String
  pulumiBackendUrl:
    Description: URL to the S3 bucket for Pulumi to store state files
    Type: String
  ecrRepo:
    Description: URL of ECR repo
    Type: String
  timestamp:
    Description: Timestamp of the deployment
    Type: String
  maxStackAgeInMinutes:
    Description: Maximum age of Pulumi stack in minutes
    Type: Number
  maxStateFileAgeInMinutes:
    Description: Maximum age of Pulumi state file in minutes
    Type: Number
  cleanupScheduleExpression:
    Description: Expression for the rogue instance cleanup scheduler. Expression as defined in https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-scheduler-schedule.html#cfn-scheduler-schedule-scheduleexpression
    Type: String

Resources:
  GHAppWebhookConsumerLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Join [ "-", [ !Ref functionName, !Ref timestamp ] ]
      Description: Basic Auth Funtion
      Role: !Ref awsRole
      MemorySize: 512
      EphemeralStorage:
        Size: 10240
      Timeout: 900
      PackageType: Image
      ImageUri: !Join [ ":", [ !Ref ecrRepo, 'latest' ] ]
      Tags:
        map-migrated: d-server-01068mdjl5jze3
      Events:
        FetchHttpApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApiGateway
            Path: /ghrunner-app
            Method: POST
        SchedulerRogueInstanceCleanup:
          Type: ScheduleV2
          Properties:
            ScheduleExpression: !Ref cleanupScheduleExpression
            Input: '{ "type": "scheduler", "name": "SchedulerRogueInstanceCleanup", "enabled": true }'
        SchedulerRemoveRemoteStateFiles:
          Type: ScheduleV2
          Properties:
            ScheduleExpression: rate(1 minute)
            Input: '{ "type": "scheduler", "name": "SchedulerRemoveRemoteStateFiles", "enabled": true }'
      Environment:
        Variables:
          PULUMI_BACKEND_URL: !Ref pulumiBackendUrl
          DEPLOYMENT_TIMESTAMP: !Ref timestamp
          MAX_STACK_AGE_IN_MINUTES: !Ref maxStackAgeInMinutes
          MAX_STATE_FILE_AGE_IN_MINUTES: !Ref maxStateFileAgeInMinutes
  
  HttpApiGateway:
    Type: AWS::Serverless::HttpApi
    Tags:
        map-migrated: d-server-01068mdjl5jze3

  CustomDomainName:
    Type: AWS::ApiGatewayV2::DomainName
    Properties: 
      DomainName: !Ref fullDomainName
      DomainNameConfigurations: 
        - EndpointType: REGIONAL
          CertificateArn: !Ref tlsCertificateArn
      Tags:
        map-migrated: d-server-01068mdjl5jze3

  HttpApiMapping:
    Type: AWS::ApiGatewayV2::ApiMapping
    Properties: 
      ApiId: !Ref HttpApiGateway
      DomainName: !Ref CustomDomainName
      Stage: !Ref HttpApiGatewayApiGatewayDefaultStage ## = {LogicalName} + ApiGateway + {StageName} + Stage

  RecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: !Ref fullDomainName
      HostedZoneId: !Ref hostedZoneId
      AliasTarget: 
        DNSName: !GetAtt CustomDomainName.RegionalDomainName
        HostedZoneId: !GetAtt CustomDomainName.RegionalHostedZoneId
      Type: A